name       : llvm-bolt
version    : 15.0.7
release    : 3
source     :
    - https://github.com/llvm/llvm-project/archive/refs/tags/llvmorg-15.0.7.tar.gz : 42a0088f148edcf6c770dfc780a7273014a9a89b66f357c761b4ca7c8dfa10ba
license    : Apache-2.0
component  : programming.tools
summary    : Binary Optimization and Layout Tool.
description: |
    Binary Optimization and Layout Tool.
patterns   :
    - /usr/lib/libbolt_rt*.a
clang      : yes
builddeps  :
    - git
setup      : |
    %cmake_ninja -S llvm -DLLVM_ENABLE_ASSERTIONS=ON \
        -DLLVM_ENABLE_PROJECTS='bolt;clang;lld' \
        -DLLVM_TARGETS_TO_BUILD='X86'
install    : |
    DESTDIR=$installdir %ninja_build install-llvm-bolt install-perf2bolt llvm-bolt-heatmap install-merge-fdata install-llvm-boltdiff install-bolt_rt
    # ???
    rm -fr $installdir/home
