name       : llvm-bolt
version    : 15.0.0
release    : 1
source     :
    - https://github.com/llvm/llvm-project/archive/05523dc32d8ca81d9a92ff955194a9e80cf79dc0.tar.gz : 50dfb039624ec5270ec09579543407a42040e57f4761b5ffd96b7366d3a28fad
license    : Apache-2.0
component  : programming.tools
summary    : Binary Optimization and Layout Tool.
description: |
    Binary Optimization and Layout Tool.
patterns   :
    - /usr/lib/libbolt_rt*.a
clang      : yes
builddeps  :
    - git
setup      : |
    %cmake_ninja -S llvm -DLLVM_ENABLE_ASSERTIONS=ON \
        -DLLVM_ENABLE_PROJECTS='bolt;clang;lld' \
        -DLLVM_TARGETS_TO_BUILD='X86'
install    : |
    DESTDIR=$installdir %ninja_build install-llvm-bolt install-perf2bolt llvm-bolt-heatmap install-merge-fdata install-llvm-boltdiff install-bolt_rt
    # ???
    rm -fr $installdir/home
